-d /home/alessandro/Desktop/HDMI_fpga_project/impl/gwsynthesis/HDMI_fpga_project.vg
-p GW2A-18C-PBGA256-8
-pn GW2A-LV18PG256C8/I7
-cst /home/alessandro/Desktop/HDMI_fpga_project/src/HDMI_fpga_project.cst
-cfg /home/alessandro/Desktop/HDMI_fpga_project/impl/pnr/device.cfg
-bit
-tr
-ph
-timing
-cst_error
-correct_hold 1
-route_maxfan 23
